var age = 45;
console.log("age is " + age);
var employeeName = "virat";
console.log("name " + employeeName);
// let available:boolean =true;
// console.log("availability : " + available);
var fruits = ['apple', 'mango', 'banana'];
console.log(fruits.length);
console.log(fruits);
var arr = ['sachin', 'ravi', 45, 90, 'virat'];
console.log(arr.length);
console.log(arr);
var msg;
var msg2;
msg = "hello";
msg = 45;
msg = true;
//msg2=true;
//msg=45;
msg = "hii";
var marks = [67, 87, 67];
var item;
item = [[1, 'laptop'], [2, 'mobile']];
item.push([3, 'toy']);
marks.push(34);
console.log(marks);
console.log(item);
var sum = "virat"; //it identifies the variable type
var month = 'january';
var months;
(function (months) {
    months["january"] = "jan";
    months["february"] = "feb";
    months["march"] = "mar";
    months["april"] = "april";
})(months || (months = {}));
var months2 = months.january;
var months3 = months.february;
var months4 = months.march;
console.log(months2);
console.log(months3);
console.log(months4);
